### ISSUE TITLE
Game seems to not render

### ISSUE THREAD

**Issue by kumavis** [mikolalysenko/lpf-ctf#2]
Just a black screen with a gray line.

![image](https://cloud.githubusercontent.com/assets/1474978/5888664/ad89c99e-a3bd-11e4-9775-d055e49030a1.png)

No errors in console. Shooting events seem to be captured and transmitted correctly.

**Comment by mikolalysenko** [comment]
Ok, I had some unpushed commits. Try the latest version

**Comment by kumavis** [comment]
beauty!
![image](https://cloud.githubusercontent.com/assets/1474978/5889027/5f595a68-a3c8-11e4-8651-4ccad3d95356.png)
