### ISSUE TITLE
User velocities for player movement!

### ISSUE THREAD

**Issue by danfinlay** [mikolalysenko/lpf-ctf#3]
Part of what makes [Tagpro](http://tagpro.gg/) (another multiplayer node-based CTF game) so compelling is the velocity and physics, which require a lot of extra player coordination, and would probably make for a better demonstration of your perception filters, and it's not a very hard layer to add!

(Rather than arrows adding position, they add velocity to that dimension towards a limit, which is applied each tick, and decays over time by some friction constant).  I'm sure you knew that but just to lay it out.

**Comment by mikolalysenko** [comment]
Sure, though this demo isn't intended to be a serious game.  I wrote as part of a conference talk which I gave for nodeconfeu.  You can find the slides here:

https://github.com/mikolalysenko/nodeconfeu2014-slides

**Comment by danfinlay** [comment]
Yeah, I figured as much.  I did watch one of your talks on this topic, it was awesome!
